# Generated by Django 6.0.4 on 2026-04-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capstoneproject",
            name="area",
        ),
        migrations.RemoveField(
            model_name="capstoneproject",
            name="image",
        ),
        migrations.RemoveField(
            model_name="capstoneproject",
            name="repository_url",
        ),
        migrations.AddField(
            model_name="capstoneproject",
            name="areas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capstoneproject",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="capstoneproject",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capstoneproject",
            name="pdf_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capstoneproject",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="capstoneproject",
            name="authors",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="capstoneproject",
            name="keywords",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="capstoneproject",
            name="teachers",
        ),
        migrations.AlterField(
            model_name="capstoneproject",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name="capstoneproject",
            name="teachers",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
